gedima_gination/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from Gedimagination.views.api.TOTPAPI import TOTPCreateView, TOTPVerifyView
from Gedimagination.views.api.customAuthToken import CustomAuthToken
from Gedimagination.views.index import index
from Gedimagination.views.contact import contact
from Gedimagination.views.registration.activate import activate
from Gedimagination.views.reglement import reglement
from Gedimagination.views.classement import classement
from Gedimagination.views.participation import *
from Gedimagination.views.registration.register import *
from Gedimagination.views.api.data import *
from Gedimagination.views.api.participations import *
from Gedimagination.views.api.apiRoot import *
from Gedimagination.views.user import user
from Gedimagination.views.admin import admin as manager

#Activation de la double authtification sur la page admin
#admin.site.__class__ = OTPAdminSite

schema_view = get_schema_view(
   openapi.Info(
      title="Gedimagination api",
      default_version='v1.0',
      description="API pour le concours Gedimagination",
      terms_of_service="",
      contact=openapi.Contact(email=""),
      license=openapi.License(name=""),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    #Gestion des comptes

    path('admin/', admin.site.urls, name='admin'),
    path("accounts/", include("django.contrib.auth.urls")),
    #path('account/', include('allauth.urls')), #Gestionnaire de connexion avec un compte google
    path('accounts/register/', register, name='register'),
    path('accounts/manager/', manager, name='manager'),
    path('accounts/user/', user, name='user'),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),

    #Sites
    path('', index, name='index'),
    path('participation/', participation, name='participation'),
    path('classement/', classement, name='classement'),
    path('reglement/', reglement, name='reglement'),
    path('contact/', contact, name='contact'),

    #API
    re_path(r'^api/swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^api/swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^api/redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    re_path(r'^totp/create/$', TOTPCreateView.as_view(), name='totp-create'),
    re_path(r'^totp/login/(?P<token>[0-9]{6})/$', TOTPVerifyView.as_view(), name='totp-login'),
    path('api/participations/', ParticipationsList.as_view()),
    path('api/participations/<int:pk>/', ParticipationsDetails.as_view()),
    path('api/data/', DataApiList.as_view()),
    path('api/data/<int:pk>/', DataApiDetails.as_view()),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api-token-auth/', CustomAuthToken.as_view(), name='api-token-auth'),
]

#Gestion des erreurs
handler418 = 'Gedimagination.views.handler.handler418'
handler400 = 'Gedimagination.views.handler.handler400'
handler401 = 'Gedimagination.views.handler.handler401'
handler403 = 'Gedimagination.views.handler.handler403'
handler404 = 'Gedimagination.views.handler.handler404'
handler500 = 'Gedimagination.views.handler.handler500'

Gedimagination/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AccountEmailaddress(models.Model):
    email = models.CharField(unique=True, max_length=254)
    verified = models.IntegerField()
    primary = models.IntegerField()
    user = models.ForeignKey('AuthUser', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'account_emailaddress'


class AccountEmailconfirmation(models.Model):
    created = models.DateTimeField()
    sent = models.DateTimeField(blank=True, null=True)
    key = models.CharField(unique=True, max_length=64)
    email_address = models.ForeignKey(AccountEmailaddress, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'account_emailconfirmation'


class Action(models.Model):
    id_action = models.AutoField(primary_key=True)
    action = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'action'


class Activation(models.Model):
    id_activation = models.AutoField(primary_key=True)
    id_user = models.ForeignKey('AuthUser', models.DO_NOTHING, db_column='id_user')
    code = models.CharField(max_length=10)
    date_code = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'activation'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class AuthtokenToken(models.Model):
    key = models.CharField(primary_key=True, max_length=40)
    created = models.DateTimeField()
    user = models.OneToOneField(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'authtoken_token'


class AxesAccessattempt(models.Model):
    user_agent = models.CharField(max_length=255)
    ip_address = models.CharField(max_length=39, blank=True, null=True)
    username = models.CharField(max_length=255, blank=True, null=True)
    http_accept = models.CharField(max_length=1025)
    path_info = models.CharField(max_length=255)
    attempt_time = models.DateTimeField()
    get_data = models.TextField()
    post_data = models.TextField()
    failures_since_start = models.PositiveIntegerField()

    class Meta:
        managed = False
        db_table = 'axes_accessattempt'
        unique_together = (('username', 'ip_address', 'user_agent'),)


class AxesAccessfailurelog(models.Model):
    user_agent = models.CharField(max_length=255)
    ip_address = models.CharField(max_length=39, blank=True, null=True)
    username = models.CharField(max_length=255, blank=True, null=True)
    http_accept = models.CharField(max_length=1025)
    path_info = models.CharField(max_length=255)
    attempt_time = models.DateTimeField()
    locked_out = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'axes_accessfailurelog'


class AxesAccesslog(models.Model):
    user_agent = models.CharField(max_length=255)
    ip_address = models.CharField(max_length=39, blank=True, null=True)
    username = models.CharField(max_length=255, blank=True, null=True)
    http_accept = models.CharField(max_length=1025)
    path_info = models.CharField(max_length=255)
    attempt_time = models.DateTimeField()
    logout_time = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'axes_accesslog'


class Consentement(models.Model):
    id_consentement = models.AutoField(primary_key=True)
    id_user = models.ForeignKey(AuthUser, models.DO_NOTHING, db_column='id_user')
    id_action = models.ForeignKey(Action, models.DO_NOTHING, db_column='id_action')
    date_consentement = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'consentement'


class Data(models.Model):
    id_data = models.AutoField(primary_key=True)
    debut_participation = models.DateField(blank=True, null=True)
    fin_participation = models.DateField(blank=True, null=True)
    debut_vote = models.DateField(blank=True, null=True)
    fin_vote = models.DateField(blank=True, null=True)
    reglement = models.TextField(blank=True, null=True)
    classement_generer = models.IntegerField()
    classement_publique = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'data'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoScrubberFakedata(models.Model):
    id = models.BigAutoField(primary_key=True)
    provider = models.CharField(max_length=255)
    provider_offset = models.PositiveSmallIntegerField()
    content = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'django_scrubber_fakedata'
        unique_together = (('provider', 'provider_offset'),)


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class DrfApiLogs(models.Model):
    id = models.BigAutoField(primary_key=True)
    added_on = models.DateTimeField()
    api = models.CharField(max_length=1024)
    headers = models.TextField()
    body = models.TextField()
    method = models.CharField(max_length=10)
    client_ip_address = models.CharField(max_length=50)
    response = models.TextField()
    status_code = models.PositiveSmallIntegerField()
    execution_time = models.DecimalField(max_digits=8, decimal_places=5)

    class Meta:
        managed = False
        db_table = 'drf_api_logs'


class OtpTotpTotpdevice(models.Model):
    name = models.CharField(max_length=64)
    confirmed = models.IntegerField()
    key = models.CharField(max_length=80)
    step = models.PositiveSmallIntegerField()
    t0 = models.BigIntegerField()
    digits = models.PositiveSmallIntegerField()
    tolerance = models.PositiveSmallIntegerField()
    drift = models.SmallIntegerField()
    last_t = models.BigIntegerField()
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    throttling_failure_count = models.PositiveIntegerField()
    throttling_failure_timestamp = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'otp_totp_totpdevice'


class Participation(models.Model):
    id_participation = models.AutoField(primary_key=True)
    id_user = models.OneToOneField(AuthUser, models.DO_NOTHING, db_column='id_user')
    image = models.CharField(max_length=255)
    description = models.CharField(max_length=255)

Gedimagination/forms/contactForm.py
from django import forms


class ContactForm(forms.Form):
    # Champs du formulaire
    full_name = forms.CharField(label='Nom et Prénom', required=True)
    email = forms.EmailField(label='Email:', required=True)
    message = forms.CharField(label="Reglement", required=True,widget=forms.Textarea)

    # Ajout des classes pour bootstrap
    full_name.widget.attrs.update({'class': 'form-control'})
    email.widget.attrs.update({'class': 'form-control'})
    message.widget.attrs.update({'class': 'form-control', 'style': 'height: 100px;'})

Gedimagination/forms/fileForm.py
from django import forms
from Gedimagination.widgets import *

from Gedimagination.lib.validator import *


class FileForm(forms.Form):
    # Champs du formulaire
    titreRealisation = forms.CharField(label="Titre de votre projet: ", required=True, max_length=254)
    descriptionRealisation = forms.CharField(label="Description de votre projet: ", required=True, max_length=254)
    dateRealisation = forms.DateField(label="Date de votre projet: ", required=True, widget=DateInput)
    photoRealisation = forms.FileField(label="Sélectionnez l'image de votre projet: ",  validators=[file_size, file_extension], max_length=254, required=True)
    consentement = forms.BooleanField(label="J'accepte que mes données soient utilisées pour la création de votre projet: ", required=True)

    # Ajout des classes pour bootstrap
    titreRealisation.widget.attrs.update({'class': 'form-control'})
    descriptionRealisation.widget.attrs.update({'class': 'form-control'})
    dateRealisation.widget.attrs.update({'class': 'form-control'})
    photoRealisation.widget.attrs.update({'class': 'form-control'})

Gedimagination/forms/loginForm.py
from django import forms


class LoginForm(forms.Form):
    dateParticipation = forms.DateField(label="Date de votre projet: ", required=True)

Gedimagination/views/classement.py
from datetime import date


from django.shortcuts import render

from Gedimagination.lib.generateClassement import get_classement
from Gedimagination.models import Data, Participation

"""
Gestion de la page classement
"""
def classement(request):
    #Variables
    date_now = date.today().strftime("%Y-%m-%d")
    data = Data.objects.first()

    # Vérification de présence d'information sur le concours
    if data is None:
        return render(request, 'error/dataError.html')
    if data.fin_vote is None:
        return render(request, 'error/dataError.html')

    fin_vote = data.fin_vote.strftime("%Y-%m-%d")
    participations = Participation.objects.filter(place_classement__range=(1,3)).order_by('place_classement')
    classement = get_classement(participations)

    return render(request, 'classement.html', {'data': data, 'date_now':date_now, 'fin_vote': fin_vote, 'classement': classement})

Gedimagination/views/contact.py
from django.shortcuts import render
from django.core.mail import send_mail

from Gedimagination.forms.contactForm import ContactForm

"""
Gestion de la page contact
"""
def contact(request):
    contact_form = ContactForm()

    if request.method == 'POST':
        contact = ContactForm(request.POST, request.FILES)
        if contact.is_valid():
            send_mail(
                'Support Gedima\'gination ' + request.POST['email'] + " " + request.POST['full_name'],
                request.POST['message'],
                'contact.gedimagination@gmail.com',
                ['contact.gedimagination@gmail.com'],
                fail_silently=True,
            )


    return render(request, 'contact.html',{'form': contact_form})

Gedimagination/views/index.py
from django.shortcuts import render



def index(request):

    return render(request, 'index.html', {})

Gedimagination/views/reglement.py
from django.shortcuts import render

from Gedimagination.models import Data

"""
Gestion de la page reglement
"""
def reglement(request):
    #Variables
    data = Data.objects.first()

    # Vérification de présence d'information sur le concours
    if data is None:
        return render(request, 'error/dataError.html')

    return render(request, 'reglement.html', {'data': data})

Gedimagination/templates/admin.html
{% extends 'base.html' %}

{% block title %}Gestionnaire{% endblock %}

{% block content %}
    <div style="min-height: 55vh;">
        {% if data.classement_generer == 1 %}
            <table class="table table-hover mt-5">
                <thead>
                <tr>
                    <th scope="col">Place</th>
                    <th scope="col">Titre de la réalisation</th>
                    <th scope="col">Description de la réalisation</th>
                    <th scope="col">Nombre de G'aime</th>
                    <th scope="col">Auteur de la réalisation</th>
                </tr>
                </thead>
                <tbody>
                {% for i in classement %}
                    {% for j in i %}
                        <tr class="table-light">
                            <th scope="row">{{ j.0 }}</th>
                            <td>{{ j.1 }}</td>
                            <td>{{ j.2 }}</td>
                            <td>{{ j.4 }}</td>
                            <td>{{ j.5 }}</td>
                        </tr>
                    {% endfor %}
                {% endfor %}
                </tbody>
            </table>
        {% endif %}

        {% if date_now < fin_vote %}
            <h1 class="text-center mb-5 mt-5">La période de vote n'est pas terminé.</h1>
        {% elif fin_vote != '' and data.classement_publique == 0 %}
            <form action="{% url 'manager' %}" method="post">
                {% csrf_token %}
                <div class="btn-group" role="group">
                    <button type="submit" name='manager_classement' value="generate" class="btn btn-primary">Génerer le
                        classement
                    </button>
                    <button type="submit" name='manager_classement' value="publish" class="btn btn-primary">Publier le
                        classement
                    </button>
                </div>
            </form>
        {% elif  data.classement_publique == 1 %}
            <h1 class="text-center mb-5 mt-5">Le classement est publique</h1>
        {% endif %}
        <div class="card border-primary mt-5 mx-auto" style="max-width: 40rem;">
            <div class="card-body">
                <h4 class="card-title text-center">Formulaire de gestion des paramètre</h4>
                <form method="post" enctype="multipart/form-data" data-bitwarden-watching="1">
                    <fieldset>
                        {% csrf_token %}
                        <div class="row row-cols-lg-auto g-3">
                            <div class="form-group col">
                                <label for="id_debut_participation" class="form-label mt-4">Debut des participations</label>
                                {{ dataForm.debut_participation }}
                            </div>
                            <div class="form-group has-danger">
                                <label for="id_fin_participation" class="form-label mt-4">Fin des participations</label>
                                {{ dataForm.fin_participation }}
                            </div>
                        </div>
                        <div class="row row-cols-lg-auto g-3">
                            <div class="form-group col">
                                <label for="id_debut_vote" class="form-label mt-4">Debut des votes</label>
                                {{ dataForm.debut_vote }}
                            </div>
                            <div class="form-group has-danger">
                                <label for="id_fin_vote" class="form-label mt-4">Fin des votes</label>
                                {{ dataForm.fin_vote }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="id_reglement" class="form-label mt-4">Reglement</label>
                            {{ dataForm.reglement }}
                        </div>
                        <button type="submit" class="btn btn-primary mt-4">Envoyer</button>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

Gedimagination/templates/classement.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Gestionnaire{% endblock %}

{% block content %}
    <div class="min-vh-100">
        {% if date_now < fin_vote %}
            <h1 class="text-center mb-5 mt-5">La période de vote n'est pas terminé.</h1>
        {% elif data.classement_publique == 1 %}
            <table class="table table-hover mt-5 ml-5 mr-5">
                <thead>
                <tr>
                    <th scope="col">Place</th>
                    <th scope="col">Titre de la réalisation</th>
                    <th scope="col">Description de la réalisation</th>
                    <th scope="col">Image de la participation</th>
                    <th scope="col">Nombre de G'aime</th>
                    <th scope="col">Auteur de la réalisation</th>
                </tr>
                </thead>
                <tbody>
                {% for i in classement %}
                    {% for j in i %}
                        <tr class="table-light">
                            <th scope="row">{{ j.0 }}</th>
                            <td>{{ j.1 }}</td>
                            <td>{{ j.2 }}</td>
                            <td><img src="{% static 'images/participation/' %}{{ j.3 }}" style="max-width:10vw; max-height: 10vh"></td>
                            <td>{{ j.4 }}</td>
                            <td>{{ j.5 }}</td>
                            <td>{{ j.6 }}</td>
                        </tr>
                    {% endfor %}
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <h1 class="text-center mb-5 mt-5">Le classement n'a pas encore été géneré</h1>
        {% endif %}
    </div>
{% endblock %}

Gedimagination/templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <div style="min-height: 55vh;">
        <div class="card border-primary mt-5 mx-auto" style="max-width: 40rem;">
            <h1 class="text-center mb-5 mt-5">Contact</h1>
            <div class="card border-primary mb- mx-auto" style="max-width: 40rem;">
                <div class="card-body mx-auto">
                    <h4 class="card-title"></h4>
                    <form method="post">
                        <fieldset>
                            {% csrf_token %}
                            <div class="row row-cols-lg-auto g-3">
                                <div class="form-group col">
                                    <label for="id_full_name" class="form-label mt-4">Nom et Prénom</label>
                                    {{ form.full_name }}
                                </div>
                                <div class="form-group has-danger">
                                    <label for="id_email" class="form-label mt-4">Email</label>
                                    {{ form.email }}
                                </div>
                            </div>
                            <div class="row row-cols-lg-auto g-3">
                                <div class="form-group">
                                    <label for="id_message" class="form-label mt-4">Message</label>
                                    {{ form.message }}
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary mt-4 mx-auto">Envoyer</button>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Gedimagination/templates/participation.html
{% extends 'base.html' %}

{% block title %}Participer{% endblock %}

{% block content %}
    <div style="min-height: 55vh;">
        <h1 class="text-center mb-5 mt-5">Participer au concours Gédima'gination 2022</h1>
        {% if date_now < debut_participation or date_now > fin_participation %}
            <div class="card border-primary mb- mx-auto" style="max-width: 20rem;">
                <div class="card-body">
                    <h4 class="card-title">Participation fermée</h4>
                    <p class="card-text">La participation au concours est fermée le concours aura lieu du
                        {{ debut_participation }} au {{ fin_participation }}</p>
                </div>
            </div>
        {% elif response == "error" %}
            <div class="card border-primary mb- mx-auto" style="max-width: 20rem;">
                <div class="card-body">
                    <h4 class="card-title">Une erreur est survenue</h4>
                    {% if virus == False %}<p class="card-text">Le fichier envoyé a été détecter comme potentiellement
                        malveillant</p>{% endif %}
                    {% if file == False %}
                        <p class="card-text">Une erreur est survenu durant le scan anti-virus</p>{% endif %}
                    {% if data == False %}
                        <p class="card-text">Une erreur est survenu lors de la sauvegarde de l'image</p>{% endif %}
                </div>
            </div>
        {% elif response == "success" %}
            <div class="card border-primary mb- mx-auto" style="max-width: 20rem;">
                <div class="card-body">
                    <h4 class="card-title">Merci de votre participation</h4>
                    <p class="card-text">Votre participation a bien été prise en compte</p>
                </div>
            </div>
        {% elif response == "alreadyExist" %}
            <div class="card border-primary mb- mx-auto" style="max-width: 20rem;">
                <div class="card-body">
                    <h4 class="card-title">Vous avez déjà participer au concours</h4>
                    <p class="card-text">Une participation est déjà enregistré avec se compte vous pouvez la consulter
                        depuis votre compte</p>
                </div>
            </div>
        {% else %}
            <div class="card border-primary mb- mx-auto" style="max-width: 40rem;">
                <div class="card-body">
                    <h4 class="card-title text-center">Formulaire de participation</h4>
                    <form method="post" enctype="multipart/form-data" data-bitwarden-watching="1">
                        <fieldset>
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="id_titreRealisation" class="form-label mt-4">Titre [*]</label>
                                {{ fileForm.titreRealisation }}
                            </div>
                            <div class="form-group">
                                <label for="id_descriptionRealisation" class="form-label mt-4">Description [*]</label>
                                {{ fileForm.descriptionRealisation }}
                            </div>
                            <div class="form-group">
                                <label for="id_dateRealisation" class="form-label mt-4">Date de la réalisation [*]</label>
                                {{ fileForm.dateRealisation }}
                            </div>
                            <div class="form-group">
                                <label for="id_photoRealisation" class="form-label mt-4">Photo de la réalisation [*] 4Mo max, jpg,jpeg,png seulement</label>
                                {{ fileForm.photoRealisation }}
                            </div>
                            <div class="form-group">
                                <label for="id_consentement" class="form-label mt-4">En soumettant ce formulaire,
                                    j'accepte que les informations saisies soient exploitées dans le cadre de la participation
                                    au concours Gedima'gination [*]
                                </label>
                                {{ fileForm.consentement }}
                            </div>
                            <button type="submit" class="btn btn-primary mt-4">Envoyer</button>
                        </fieldset>
                    </form>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}